// File generated by flutterfire_cli.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Platform-specific Firebase options
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLBMkDB_UVOj2fvqbMuoDhUs-HAy2hg9E',
    appId: '1:215465833827:web:a06958874b4b7e75af0f56',
    messagingSenderId: '215465833827',
    projectId: 'ironflow-5b79d',
    authDomain: 'ironflow-5b79d.firebaseapp.com',
    storageBucket: 'ironflow-5b79d.firebasestorage.app',
    measurementId: 'G-QSX6LYSWVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Brzp6gIKiogXOPXm0Xm3MCEPmamd_Z8',
    appId: '1:215465833827:android:c314e6797303209caf0f56',
    messagingSenderId: '215465833827',
    projectId: 'ironflow-5b79d',
    storageBucket: 'ironflow-5b79d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: '215465833827',
    projectId: 'ironflow-5b79d',
    storageBucket: 'ironflow-5b79d.firebasestorage.app',
    iosBundleId: 'com.progressiontracker.progressionTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: '215465833827',
    projectId: 'ironflow-5b79d',
    storageBucket: 'ironflow-5b79d.firebasestorage.app',
    iosBundleId: 'com.progressiontracker.progressionTracker.macos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: '215465833827',
    projectId: 'ironflow-5b79d',
    storageBucket: 'ironflow-5b79d.firebasestorage.app',
  );
}
