// Mocks generated by Mockito 5.4.6 from annotations
// in progression_tracker/test/features/ai/mocks/mock_repositories.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:progression_tracker/features/body/domain/entities/body_entry.dart'
    as _i8;
import 'package:progression_tracker/features/body/domain/repositories/body_repository.dart'
    as _i7;
import 'package:progression_tracker/features/nutrition/domain/entities/entities.dart'
    as _i2;
import 'package:progression_tracker/features/nutrition/domain/repositories/nutrition_repository.dart'
    as _i6;
import 'package:progression_tracker/features/workout/domain/entities/entities.dart'
    as _i5;
import 'package:progression_tracker/features/workout/domain/repositories/workout_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDailyNutritionSummary_0 extends _i1.SmartFake
    implements _i2.DailyNutritionSummary {
  _FakeDailyNutritionSummary_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WorkoutRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutRepository extends _i1.Mock implements _i3.WorkoutRepository {
  MockWorkoutRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveWorkout(_i5.Workout? workout) =>
      (super.noSuchMethod(
            Invocation.method(#saveWorkout, [workout]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.Workout>> getAllWorkouts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllWorkouts, []),
            returnValue: _i4.Future<List<_i5.Workout>>.value(<_i5.Workout>[]),
          )
          as _i4.Future<List<_i5.Workout>>);

  @override
  _i4.Future<List<_i5.Workout>> getWorkoutsPaginated({
    int? offset = 0,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutsPaginated, [], {
              #offset: offset,
              #limit: limit,
            }),
            returnValue: _i4.Future<List<_i5.Workout>>.value(<_i5.Workout>[]),
          )
          as _i4.Future<List<_i5.Workout>>);

  @override
  _i4.Future<int> getWorkoutCount() =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutCount, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i5.Workout>> getWorkoutsByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutsByDateRange, [start, end]),
            returnValue: _i4.Future<List<_i5.Workout>>.value(<_i5.Workout>[]),
          )
          as _i4.Future<List<_i5.Workout>>);

  @override
  _i4.Future<List<_i5.Exercise>> getExerciseHistory(
    String? exerciseName,
    int? limit,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseHistory, [exerciseName, limit]),
            returnValue: _i4.Future<List<_i5.Exercise>>.value(<_i5.Exercise>[]),
          )
          as _i4.Future<List<_i5.Exercise>>);

  @override
  _i4.Future<void> deleteWorkout(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkout, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [NutritionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNutritionRepository extends _i1.Mock
    implements _i6.NutritionRepository {
  MockNutritionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DailyNutritionSummary> getDailyNutrition(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getDailyNutrition, [date]),
            returnValue: _i4.Future<_i2.DailyNutritionSummary>.value(
              _FakeDailyNutritionSummary_0(
                this,
                Invocation.method(#getDailyNutrition, [date]),
              ),
            ),
          )
          as _i4.Future<_i2.DailyNutritionSummary>);

  @override
  _i4.Future<void> saveMealEntry(_i2.Meal? meal) =>
      (super.noSuchMethod(
            Invocation.method(#saveMealEntry, [meal]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.DailyNutritionSummary>> getNutritionHistory(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNutritionHistory, [startDate, endDate]),
            returnValue: _i4.Future<List<_i2.DailyNutritionSummary>>.value(
              <_i2.DailyNutritionSummary>[],
            ),
          )
          as _i4.Future<List<_i2.DailyNutritionSummary>>);

  @override
  _i4.Future<List<_i2.DailyNutritionSummary>> getNutritionHistoryPaginated({
    int? offset = 0,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNutritionHistoryPaginated, [], {
              #offset: offset,
              #limit: limit,
            }),
            returnValue: _i4.Future<List<_i2.DailyNutritionSummary>>.value(
              <_i2.DailyNutritionSummary>[],
            ),
          )
          as _i4.Future<List<_i2.DailyNutritionSummary>>);

  @override
  _i4.Future<int> getNutritionHistoryCount() =>
      (super.noSuchMethod(
            Invocation.method(#getNutritionHistoryCount, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<_i2.NutritionTargets?> getNutritionTargets() =>
      (super.noSuchMethod(
            Invocation.method(#getNutritionTargets, []),
            returnValue: _i4.Future<_i2.NutritionTargets?>.value(),
          )
          as _i4.Future<_i2.NutritionTargets?>);

  @override
  _i4.Future<void> saveNutritionTargets(_i2.NutritionTargets? targets) =>
      (super.noSuchMethod(
            Invocation.method(#saveNutritionTargets, [targets]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteMealEntry(String? mealId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMealEntry, [mealId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Meal>> getMealsByDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getMealsByDate, [date]),
            returnValue: _i4.Future<List<_i2.Meal>>.value(<_i2.Meal>[]),
          )
          as _i4.Future<List<_i2.Meal>>);

  @override
  _i4.Future<void> clearAllData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllData, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [BodyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBodyRepository extends _i1.Mock implements _i7.BodyRepository {
  MockBodyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveBodyEntry(_i8.BodyEntry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#saveBodyEntry, [entry]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i8.BodyEntry>> getAllBodyEntries() =>
      (super.noSuchMethod(
            Invocation.method(#getAllBodyEntries, []),
            returnValue: _i4.Future<List<_i8.BodyEntry>>.value(
              <_i8.BodyEntry>[],
            ),
          )
          as _i4.Future<List<_i8.BodyEntry>>);

  @override
  _i4.Future<List<_i8.BodyEntry>> getBodyEntriesByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBodyEntriesByDateRange, [start, end]),
            returnValue: _i4.Future<List<_i8.BodyEntry>>.value(
              <_i8.BodyEntry>[],
            ),
          )
          as _i4.Future<List<_i8.BodyEntry>>);

  @override
  _i4.Future<void> deleteBodyEntry(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBodyEntry, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
