// Mocks generated by Mockito 5.4.6 from annotations
// in progression_tracker/test/features/ai/presentation/providers/global_ai_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:progression_tracker/features/ai/domain/entities/insight.dart'
    as _i2;
import 'package:progression_tracker/features/ai/domain/entities/insight_cache.dart'
    as _i11;
import 'package:progression_tracker/features/ai/domain/entities/insight_generation_context.dart'
    as _i6;
import 'package:progression_tracker/features/ai/domain/services/ai_insights_engine.dart'
    as _i4;
import 'package:progression_tracker/features/ai/domain/services/change_detection_service.dart'
    as _i12;
import 'package:progression_tracker/features/ai/domain/services/insight_cache_service.dart'
    as _i10;
import 'package:progression_tracker/features/body/domain/entities/body_entry.dart'
    as _i9;
import 'package:progression_tracker/features/body/domain/repositories/body_repository.dart'
    as _i17;
import 'package:progression_tracker/features/nutrition/domain/entities/daily_nutrition_summary.dart'
    as _i3;
import 'package:progression_tracker/features/nutrition/domain/entities/entities.dart'
    as _i16;
import 'package:progression_tracker/features/nutrition/domain/entities/nutrition_targets.dart'
    as _i8;
import 'package:progression_tracker/features/nutrition/domain/repositories/nutrition_repository.dart'
    as _i15;
import 'package:progression_tracker/features/workout/domain/entities/entities.dart'
    as _i14;
import 'package:progression_tracker/features/workout/domain/entities/workout.dart'
    as _i7;
import 'package:progression_tracker/features/workout/domain/repositories/workout_repository.dart'
    as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInsight_0 extends _i1.SmartFake implements _i2.Insight {
  _FakeInsight_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDailyNutritionSummary_1 extends _i1.SmartFake
    implements _i3.DailyNutritionSummary {
  _FakeDailyNutritionSummary_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AIInsightsEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockAIInsightsEngine extends _i1.Mock implements _i4.AIInsightsEngine {
  MockAIInsightsEngine() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.Insight>> generateInsights(
    _i6.InsightGenerationContext? context,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateInsights, [context]),
            returnValue: _i5.Future<List<_i2.Insight>>.value(<_i2.Insight>[]),
          )
          as _i5.Future<List<_i2.Insight>>);

  @override
  _i5.Future<_i2.Insight> generateQuickFeedback(
    _i7.Workout? completedWorkout,
    List<_i7.Workout>? history,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateQuickFeedback, [
              completedWorkout,
              history,
            ]),
            returnValue: _i5.Future<_i2.Insight>.value(
              _FakeInsight_0(
                this,
                Invocation.method(#generateQuickFeedback, [
                  completedWorkout,
                  history,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.Insight>);

  @override
  double calculateVolume(_i7.Workout? workout) =>
      (super.noSuchMethod(
            Invocation.method(#calculateVolume, [workout]),
            returnValue: 0.0,
          )
          as double);

  @override
  bool detectProgressiveOverload(List<_i7.Workout>? workouts) =>
      (super.noSuchMethod(
            Invocation.method(#detectProgressiveOverload, [workouts]),
            returnValue: false,
          )
          as bool);

  @override
  double calculateProteinDeficit(
    List<_i3.DailyNutritionSummary>? nutrition,
    _i8.NutritionTargets? targets,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#calculateProteinDeficit, [nutrition, targets]),
            returnValue: 0.0,
          )
          as double);

  @override
  _i4.WeightTrend analyzeWeightTrend(List<_i9.BodyEntry>? entries) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeWeightTrend, [entries]),
            returnValue: _i4.WeightTrend.increasing,
          )
          as _i4.WeightTrend);
}

/// A class which mocks [InsightCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockInsightCacheService extends _i1.Mock
    implements _i10.InsightCacheService {
  MockInsightCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i11.InsightCache?> getCachedInsights(
    _i2.InsightContext? context,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedInsights, [context]),
            returnValue: _i5.Future<_i11.InsightCache?>.value(),
          )
          as _i5.Future<_i11.InsightCache?>);

  @override
  _i5.Future<void> cacheInsights(_i11.InsightCache? cache) =>
      (super.noSuchMethod(
            Invocation.method(#cacheInsights, [cache]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> invalidateCache(_i2.InsightContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#invalidateCache, [context]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool isCacheStale(_i11.InsightCache? cache) =>
      (super.noSuchMethod(
            Invocation.method(#isCacheStale, [cache]),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [ChangeDetectionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChangeDetectionService extends _i1.Mock
    implements _i12.ChangeDetectionService {
  MockChangeDetectionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> hasWorkoutDataChanged(DateTime? lastGenerated) =>
      (super.noSuchMethod(
            Invocation.method(#hasWorkoutDataChanged, [lastGenerated]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> hasNutritionDataChanged(DateTime? lastGenerated) =>
      (super.noSuchMethod(
            Invocation.method(#hasNutritionDataChanged, [lastGenerated]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> hasBodyDataChanged(DateTime? lastGenerated) =>
      (super.noSuchMethod(
            Invocation.method(#hasBodyDataChanged, [lastGenerated]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<DateTime?> getLastDataChange(_i2.InsightContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#getLastDataChange, [context]),
            returnValue: _i5.Future<DateTime?>.value(),
          )
          as _i5.Future<DateTime?>);
}

/// A class which mocks [WorkoutRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutRepository extends _i1.Mock implements _i13.WorkoutRepository {
  MockWorkoutRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> saveWorkout(_i7.Workout? workout) =>
      (super.noSuchMethod(
            Invocation.method(#saveWorkout, [workout]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.Workout>> getAllWorkouts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllWorkouts, []),
            returnValue: _i5.Future<List<_i7.Workout>>.value(<_i7.Workout>[]),
          )
          as _i5.Future<List<_i7.Workout>>);

  @override
  _i5.Future<List<_i7.Workout>> getWorkoutsPaginated({
    int? offset = 0,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutsPaginated, [], {
              #offset: offset,
              #limit: limit,
            }),
            returnValue: _i5.Future<List<_i7.Workout>>.value(<_i7.Workout>[]),
          )
          as _i5.Future<List<_i7.Workout>>);

  @override
  _i5.Future<int> getWorkoutCount() =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutCount, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<_i7.Workout>> getWorkoutsByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutsByDateRange, [start, end]),
            returnValue: _i5.Future<List<_i7.Workout>>.value(<_i7.Workout>[]),
          )
          as _i5.Future<List<_i7.Workout>>);

  @override
  _i5.Future<List<_i14.Exercise>> getExerciseHistory(
    String? exerciseName,
    int? limit,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseHistory, [exerciseName, limit]),
            returnValue: _i5.Future<List<_i14.Exercise>>.value(
              <_i14.Exercise>[],
            ),
          )
          as _i5.Future<List<_i14.Exercise>>);

  @override
  _i5.Future<void> deleteWorkout(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkout, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [NutritionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNutritionRepository extends _i1.Mock
    implements _i15.NutritionRepository {
  MockNutritionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.DailyNutritionSummary> getDailyNutrition(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getDailyNutrition, [date]),
            returnValue: _i5.Future<_i3.DailyNutritionSummary>.value(
              _FakeDailyNutritionSummary_1(
                this,
                Invocation.method(#getDailyNutrition, [date]),
              ),
            ),
          )
          as _i5.Future<_i3.DailyNutritionSummary>);

  @override
  _i5.Future<void> saveMealEntry(_i16.Meal? meal) =>
      (super.noSuchMethod(
            Invocation.method(#saveMealEntry, [meal]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.DailyNutritionSummary>> getNutritionHistory(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNutritionHistory, [startDate, endDate]),
            returnValue: _i5.Future<List<_i3.DailyNutritionSummary>>.value(
              <_i3.DailyNutritionSummary>[],
            ),
          )
          as _i5.Future<List<_i3.DailyNutritionSummary>>);

  @override
  _i5.Future<List<_i3.DailyNutritionSummary>> getNutritionHistoryPaginated({
    int? offset = 0,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNutritionHistoryPaginated, [], {
              #offset: offset,
              #limit: limit,
            }),
            returnValue: _i5.Future<List<_i3.DailyNutritionSummary>>.value(
              <_i3.DailyNutritionSummary>[],
            ),
          )
          as _i5.Future<List<_i3.DailyNutritionSummary>>);

  @override
  _i5.Future<int> getNutritionHistoryCount() =>
      (super.noSuchMethod(
            Invocation.method(#getNutritionHistoryCount, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<_i8.NutritionTargets?> getNutritionTargets() =>
      (super.noSuchMethod(
            Invocation.method(#getNutritionTargets, []),
            returnValue: _i5.Future<_i8.NutritionTargets?>.value(),
          )
          as _i5.Future<_i8.NutritionTargets?>);

  @override
  _i5.Future<void> saveNutritionTargets(_i8.NutritionTargets? targets) =>
      (super.noSuchMethod(
            Invocation.method(#saveNutritionTargets, [targets]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteMealEntry(String? mealId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMealEntry, [mealId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i16.Meal>> getMealsByDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getMealsByDate, [date]),
            returnValue: _i5.Future<List<_i16.Meal>>.value(<_i16.Meal>[]),
          )
          as _i5.Future<List<_i16.Meal>>);

  @override
  _i5.Future<void> clearAllData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllData, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [BodyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBodyRepository extends _i1.Mock implements _i17.BodyRepository {
  MockBodyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> saveBodyEntry(_i9.BodyEntry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#saveBodyEntry, [entry]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i9.BodyEntry>> getAllBodyEntries() =>
      (super.noSuchMethod(
            Invocation.method(#getAllBodyEntries, []),
            returnValue: _i5.Future<List<_i9.BodyEntry>>.value(
              <_i9.BodyEntry>[],
            ),
          )
          as _i5.Future<List<_i9.BodyEntry>>);

  @override
  _i5.Future<List<_i9.BodyEntry>> getBodyEntriesByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBodyEntriesByDateRange, [start, end]),
            returnValue: _i5.Future<List<_i9.BodyEntry>>.value(
              <_i9.BodyEntry>[],
            ),
          )
          as _i5.Future<List<_i9.BodyEntry>>);

  @override
  _i5.Future<void> deleteBodyEntry(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBodyEntry, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
